-- AlterTable
ALTER TABLE "Invoice" 
ADD COLUMN "bankName" TEXT DEFAULT 'BANK MANDIRI',
ADD COLUMN "bankAccount" TEXT DEFAULT '1370024220468',
ADD COLUMN "bankHolder" TEXT DEFAULT 'FARIS DWI RAMADHAN';
